### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'

### ISSUE THREAD

**Issue by canivel** [suriyadeepan/easy_seq2seq#39]
Hi guys, Im trying to running it into a python3.5, tf 1.0.1 and I'm getting this:

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'

I already have installed the tensorflow.models into the tensorflow, but cant find the seq2seq anywhere to update it.

What should I do?

**Comment by AkishinoShiame** [comment]
I'm using the older version of tensorflow (0.12.1) without problem.

**Comment by Denisolt** [comment]
@canivel use virtual environment and install tensorflow 0.12

**Comment by sowntharsakthi** [comment]
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'Seq2Seq'....how to solve it..

**Comment by vivek9237** [comment]
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq' ...need help here @suriyadeepan

**Comment by Denisolt** [comment]
@vivek9237 try what I wrote above.

**Comment by blueseasky** [comment]
I change the version of my tensorflow  from 1.4.0 to 0.12.1,and solve the problem. But I don`t know why.

**Comment by AkishinoShiame** [comment]
See the change log of tensorflow then it will be clear.
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md
After update to 1.0.0 and above, they change the location of seq2seq from tf.nn.seq2seq to tf.contrib.legacy_seq2seq
https://www.tensorflow.org/api_docs/python/tf/contrib/legacy_seq2seq

**Comment by manav1289** [comment]
use tensorflow.contrib.seq2seq wherever tensorflow.python.ops.nn you have written
it worked for me
